language: node_js
node_js:
- '6'
script: bash ./gh-pages-deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "1bc2a8e2d590"
  - COMMIT_AUTHOR_EMAIL: "sveinung.rosaker@finn.no"
cache:
  npm: true
  directories:
  - node_modules
